data:
  root: "data/"
  batch_size: 64
model:
  d_model: 64
  gin_layers: 3
  mamba_layers: 1
  mamba_conv: 4
  mamba_state: 8
  bidirectional: true
  dropout: 0.4
training:
  epochs: 50
  lr: 0.001
  weight_decay: 0.01


# data:
#   root: "data/"
#   batch_size: 64
# model:
#   d_model: 32
#   gin_layers: 2
#   mamba_layers: 1
#   dropout: 0.3
# training:
#   epochs: 50
#   lr: 0.001
#   weight_decay: 1e-4